### ISSUE TITLE
Wrong z-coordinate for fire in cfast 

### ISSUE THREAD

**Issue by akrasuski** [aamks/aamks#16]
Z-coordinate for firein cfast.in  (line FIRE) is badly calculated. Z should be calculated with relation to local room coordinates, instead of global building coordinates. 
Please change also the ids for staircases.

**Comment by mimooh** [comment]
I will gladly fix that, but could you or mzimny provide the samples of
faulty (current) results versus the expected results? The samples
should contain the input cad.json and cfast.in. We have two issues as
I get it: (1) faulty staircases ids and (2) faulty z-coordinates.

**Comment by akrasuski** [comment]
Bad lines:
ONEZ,**1000001**
HVENT,**7,1000001**,3,0.9,2.0,0.0,1.74,2,0
FIRE,7,11.82,1.73,**4.52**,1,TIME,0,0,0,0,medium


Good:
ONEZ,**5**
HVENT**,5,7**,3,0.9,2.0,0.0,1.74,2,0
FIRE,7,11.82,1.73**,1.02**,1,TIME,0,0,0,0,medium
[cad_json.txt](https://github.com/aamks/aamks/files/3427887/cad_json.txt)

**Comment by mimooh** [comment]
Fixed in master. Hopefully works as requested. Demo/three/cad.json was updated to provide the test case for this issue.

**Comment by akrasuski** [comment]
There is still a problem with fire z-dimension. It should also be relative to the room where the fire takes place.

**Comment by mimooh** [comment]
Fixed in master

**Comment by akrasuski** [comment]
I can't check it because of such an error:

Aamks is halting on error:
Traceback (most recent call last): File "aamks.py", line 22, in EvacMcarlo() File "/usr/local/aamks.master/montecarlo/evac_mcarlo.py", line 51, in __init__ self._make_evac_conf() File "/usr/local/aamks.master/montecarlo/evac_mcarlo.py", line 187, in _make_evac_conf self._evac_conf['FLOORS_DATA'][floor]['EVACUEES'][e_id]['COMPA'] = (pos[2]) IndexError: tuple index out of range

**Comment by akrasuski** [comment]
The issue solved this is other problem.
